#!/usr/bin/env bash
set -eux -o pipefail

cd $TRAVIS_BUILD_DIR
# Exit early if there were no client changes.
.ci/changes-in-dir client || exit 0

docker build -t corla-client -f docker/test/Dockerfile.client client

popd
