#!/usr/bin/env bash
set -eux -o pipefail

cd $TRAVIS_BUILD_DIR
# Exit early if there were no server changes.
.ci/changes-in-dir server || exit 0

docker build -t corla-server -f docker/test/Dockerfile.server server

popd
